force-app/main/default/objects/TwitchUser__c/TwitchUser__c.object-meta.xml
<CustomObject>
    <description>Object representing a Twitch broadcaster</description>
    <label>Twitch User</label>
    <nameField>
        <label>Twitch User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchUser__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <description>Access Token of the twitch broadcaster</description>
    <label>Access Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/BroadcasterType__c.field-meta.xml
<CustomField>
    <fullName>BroadcasterType__c</fullName>
    <label>Broadcaster Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Twitch broadcaster</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <description>Display Name of the twitch broadcaster</description>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/LogoUrl__c.field-meta.xml
<CustomField>
    <fullName>LogoUrl__c</fullName>
    <label>Logo Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/OfflineLogoUrl__c.field-meta.xml
<CustomField>
    <fullName>OfflineLogoUrl__c</fullName>
    <label>Offline Logo Url</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>RefreshToken</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/TwitchId__c.field-meta.xml
<CustomField>
    <fullName>TwitchId__c</fullName>
    <description>Id of the Twitch Broadcaster</description>
    <externalId>true</externalId>
    <label>TwitchId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Global Mod</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <label>View Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FtbTwitchUserUtility.cls
public with sharing class FtbTwitchUserUtility extends FtbTwitchBaseClass{

    private Map<String, String> broadcasterTypeMap = new Map<String, String>{
            'partner' => 'Partner',
            'affiliate' => 'Affiliate',
            '' => ''
        };

    private Map<String, String> userType = new Map<String, String>{
        'admin' => 'Admin',
        'global_mod' => 'Global Mod',
        'staff' => 'Staff'
    };


    public TwitchUser__c createTwitchUser(FtbTwitchMonitorDto.TwitchUserResponseData userResData){
        return new TwitchUser__c(
            Name=userResData.login,
            TwitchId__c=userResData.id,
            DisplayName__c=userResData.display_name,
            LogoUrl__c=userResData.profile_image_url,
            OfflineLogoUrl__c=userResData.offline_image_url,
            Description__c=userResData.description,
            ViewCount__c=userResData.view_count,
            BroadcasterType__c=this.broadcasterTypeMap.get(userResData.broadcaster_type),
            UserType__c=this.userType.get(userResData.type)
        );
    }

    public string getTwitchUsername(){
        String sessionId = this.getTwitchSessionId();

        TwitchUser__c twitchUser = getTwitchUserByTwitchId(sessionId);

        return twitchUser.DisplayName__c;
    }

    public string getTwitchUserId(){
        String sessionId = this.getTwitchSessionId();

        TwitchUser__c twitchUser = getTwitchUserByTwitchId(sessionId);

        return twitchUser.TwitchId__c;
    }

    public TwitchUser__c getTwitchUserBySessionId(){
        String sessionId = this.getTwitchSessionId();

        return getTwitchUserByTwitchId(sessionId);
    
    }

    public TwitchUser__c getTwitchUserByTwitchId(String twitchId){

        List<TwitchUser__c> twitchUsers = FtbTwitchDbOps.getSobject([SELECT Id, 
            Name, 
            DisplayName__c, 
            TwitchId__c, 
            LogoUrl__c, 
            Description__c, 
            AccessToken__c, 
            RefreshToken__c, 
            OfflineLogoUrl__c, 
            ViewCount__c, 
            UserType__c, 
            BroadcasterType__c 
            FROM TwitchUser__c  
            WHERE TwitchId__c = :twitchId]);
        
        if(twitchUsers.isEmpty()){
            throw new FtbTwitchException('No user found for twitch id: ' + twitchId, 
            String.valueOf(FtbTwitchEnums.FtbTwitchErrors.GENERIC_ERROR));
        }

        return twitchUsers[0];
    }

}