force-app/main/default/objects/TwitchLog__c/TwitchLog__c.object-meta.xml
<CustomObject>
    <label>Twitch Log</label>
    <nameField>
        <label>Twitch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchSession__c/TwitchSession__c.object-meta.xml
<CustomObject>
    <description>Object to store sessions during twitch related operations and get it back when needed</description>
    <label>Twitch Session</label>
    <nameField>
        <label>Twitch Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchSession__c/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>Represent the key value to retrieve the session</description>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FtbTwitchBaseClass.cls
public abstract with sharing class FtbTwitchBaseClass {

    public virtual TwitchLog__c logRequest(String reqBody, TwitchLog__c log){
        throw new FtbTwitchException('Unimplemented method', String.valueOf(FtbTwitchEnums.FtbTwitchErrors.UNIMPLEMENTED_ERROR));
    }

    public virtual TwitchLog__c logResponse(String resBody, Integer statusCode, TwitchLog__c log){
        throw new FtbTwitchException('Unimplemented method', String.valueOf(FtbTwitchEnums.FtbTwitchErrors.UNIMPLEMENTED_ERROR));
    }

    protected String encryptBody(String body){
        String algo = 'AES128';
        Blob key = Crypto.generateAesKey(128);
        Blob data = Blob.valueOf(body);
        return String.valueOf(Crypto.encryptWithManagedIV(algo, key, data));
    }

    protected TwitchSession__c createTwitchSession(String sessionId){
        return new TwitchSession__c(
            Name=sessionId,
            SessionId__c=sessionId);
    }

    protected String getTwitchSessionId(){
        List<TwitchSession__c> sessions = SOQL.of(TwitchSession__c.SObjectType)
            .with(TwitchSession__c.SessionId__c)
            .whereAre(SOQL.Filter.with(TwitchSession__c.CreatedById).equal(UserInfo.getUserId()))
            .orderBy(TwitchSession__c.CreatedDate)
            .sortDesc()
            .setLimit(1)
            .mockId('FtbTwitchUserUtility.getTwitchSessionId')
            .toList();
        
        if(sessions.isEmpty() || (!sessions.isEmpty() && String.isBlank(sessions[0].SessionId__c))){
            throw new FtbTwitchException('No session found', String.valueOf(FtbTwitchEnums.FtbTwitchErrors.AUTH_ERROR));
        }

        return sessions[0].SessionId__c;
    }

}