force-app/main/default/objects/TwitchScope__c/TwitchScope__c.object-meta.xml
<CustomObject>
    <description>List all the twitch scopes grant</description>
    <label>Twitch Scope</label>
    <nameField>
        <label>Twitch Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Scopes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchScope__c/fields/ScopeApiName__c.field-meta.xml
<CustomField>
    <fullName>ScopeApiName__c</fullName>
    <label>Scope Api Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwitchScope__c/fields/Suggested__c.field-meta.xml
<CustomField>
    <fullName>Suggested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suggested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/TwitchUser__c.object-meta.xml
<CustomObject>
    <description>Object representing a Twitch broadcaster</description>
    <label>Twitch User</label>
    <nameField>
        <label>Twitch User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchUser__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Twitch broadcaster</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TwitchUserScope__c/TwitchUserScope__c.object-meta.xml
<CustomObject>
    <description>Tracks all the scopes that the user selected</description>
    <label>Twitch User Scope</label>
    <nameField>
        <label>Twitch User Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch User Scopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchUserScope__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the scope is active for the user</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TwitchUserScope__c/fields/TwitchScope__c.field-meta.xml
<CustomField>
    <fullName>TwitchScope__c</fullName>
    <label>Twitch Scope</label>
    <referenceTo>TwitchScope__c</referenceTo>
    <relationshipLabel>Twitch User Scopes</relationshipLabel>
    <relationshipName>Twitch_User_Scopes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TwitchUserScope__c/fields/TwitchUser__c.field-meta.xml
<CustomField>
    <fullName>TwitchUser__c</fullName>
    <label>Twitch User</label>
    <referenceTo>TwitchUser__c</referenceTo>
    <relationshipLabel>Twitch User Scopes</relationshipLabel>
    <relationshipName>TwitchUserScopes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FtbTwitchScopePickerService.cls
public with sharing class FtbTwitchScopePickerService {

    public static FtbTwitchUserUtility twitchUserUtility = new FtbTwitchUserUtility();


    public static FtbTwitchMonitorDto.TwitchScopePickerDto getOrganizedScopes(){

        FtbTwitchMonitorDto.TwitchScopePickerDto result = new FtbTwitchMonitorDto.TwitchScopePickerDto();
        result.organizedScopes = new Map<String, FtbTwitchMonitorDto.TwitchScope>();
        result.suggestedScopes = new List<String>();
        result.boxListScopes = new List<FtbTwitchMonitorDto.TwitchScopeBoxListDto>();
 

        List<TwitchScope__c> scopes = getAllScopes();
        for(TwitchScope__c scope: scopes){
            result.organizedScopes.put(scope.ScopeApiName__c, 
                new FtbTwitchMonitorDto.TwitchScope(scope.Name, scope.Description__c, scope.Suggested__c));
            result.boxListScopes.add(new FtbTwitchMonitorDto.TwitchScopeBoxListDto(scope.Name, scope.ScopeApiName__c));
            if(scope.Suggested__c){
                result.suggestedScopes.add(scope.ScopeApiName__c);
            }

        }
        return result;

    }

    public static void upsertAdditionalScopes(String additionalScopes){

        List<String> scopes = (FtbTwitchConstants.DEFAULT_SCOPES + ' ' + additionalScopes).split(' ');
        List<TwitchUserScope__c> scopesToUpsert = new List<TwitchUserScope__c>();


        String twitchUserId = twitchUserUtility.getTwitchUserBySessionId().Id;

        try{

            Map<String, TwitchScope__c> scopeMap = (Map<String, TwitchScope__c>) SOQL.of(TwitchScope__c.SObjectType)
                .with(TwitchScope__c.ScopeApiName__c)
                .whereAre(SOQL.Filter.with(TwitchScope__c.ScopeApiName__c).isIn(scopes))
                .mockId('FtbTwitchScopePickerService.upsertAdditionalScopes')
                .toMap(TwitchScope__c.ScopeApiName__c);
    
            Map<String, TwitchUserScope__c> existingUserScopesMap = (Map<String, TwitchUserScope__c>) SOQL.of(TwitchUserScope__c.SObjectType)
                .with(TwitchUserScope__c.Id)
                .with('TwitchScope__r', TwitchScope__c.ScopeApiName__c)
                .whereAre(SOQL.Filter.with(TwitchUserScope__c.TwitchUser__c).equal(twitchUserId))
                .mockId('FtbTwitchScopePickerService.upsertAdditionalScopes.existingUserScopesMap')
                .toMap('TwitchScope__r', TwitchScope__c.ScopeApiName__c);
    
            for(String scope : scopes){
    
                if(scopeMap.get(scope) == null){
                    continue;
                }
    
                if(existingUserScopesMap.get(scope) != null){
                    existingUserScopesMap.remove(scope);
                    continue;
                }
                TwitchUserScope__c userScope = new TwitchUserScope__c(
                    TwitchUser__c = twitchUserId,
                    TwitchScope__c = scopeMap.get(scope).Id,
                    Active__c = true
                );
                scopesToUpsert.add(userScope);
    
            }
    
            /* Deactivate existing scopes that have not been selected */
            for(TwitchUserScope__c existingScope : existingUserScopesMap.values()){
                scopesToUpsert.add(new TwitchUserScope__c(
                    Id = existingScope.Id,
                    Active__c = false
                ));
            }
    
            new DML()
                .toUpsert(scopesToUpsert)
                .commitWork();

        }catch(Exception e){
            throw new FtbTwitchException('Error upserting additional scopes: ' + e.getMessage());
        }

    }

    private static List<TwitchScope__c> getAllScopes(){

        return SOQL.of(TwitchScope__c.SObjectType)
            .with(TwitchScope__c.Description__c, TwitchScope__c.Name,
                  TwitchScope__c.Suggested__c,
                  TwitchScope__c.ScopeApiName__c)
            .whereAre(SOQL.Filter.with(TwitchScope__c.Active__c).isTrue())
            .mockId('FtbTwitchScopePickerService.getAllScopes')
            .toList();
 
    }


}