force-app/main/default/objects/TwitchApp__c/TwitchApp__c.object-meta.xml
<CustomObject>
    <description>Represent the application created via the Twtich Developer Console</description>
    <label>Twitch App</label>
    <nameField>
        <label>Twitch App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchApp__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the application is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client ID</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the app is the org default</description>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FtbTwitchUtility.cls
public with sharing class FtbTwitchUtility extends FtbTwitchBaseClass{

    public FtbTwitchUtility(){
        super();
    }

    public static List<TwitchApp__c> getTwitchApp(String appName){
        throw new FtbTwitchException('Unimplemented method', String.valueOf(FtbTwitchEnums.FtbTwitchErrors.UNIMPLEMENTED_ERROR));
    }

    // This signature of the method get the default app
    public static List<TwitchApp__c> getTwitchApp(){

        List<TwitchApp__c> res = (List<TwitchApp__c>)FtbTwitchDbOps.getSobject([SELECT ClientId__c, ClientSecret__c FROM TwitchApp__c WHERE Active__c = true AND Default__c = true]);

        if(res.isEmpty()){
            throw new FtbTwitchException('No active app credentials found', String.valueOf(FtbTwitchEnums.FtbTwitchErrors.AUTH_ERROR));
        }

        return res;
    }



}