force-app/main/default/objects/TwitchApp__c/TwitchApp__c.object-meta.xml
<CustomObject>
    <description>Represent the application created via the Twtich Developer Console</description>
    <label>Twitch App</label>
    <nameField>
        <label>Twitch App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchApp__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client ID</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/TwitchUser__c.object-meta.xml
<CustomObject>
    <description>Object representing a Twitch broadcaster</description>
    <label>Twitch User</label>
    <nameField>
        <label>Twitch User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchUser__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <description>Access Token of the twitch broadcaster</description>
    <label>Access Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchUser__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>RefreshToken</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/FtbTwitchAuthUser.cls
public with sharing class FtbTwitchAuthUser implements FtbITwitchInvokeStrategy{

    FtbTwitchUserUtility userUtilityClass = new FtbTwitchUserUtility();
    TwitchUser__c twitchUser;

    public FtbTwitchAuthUser(){
        this.twitchUser = userUtilityClass.getTwitchUserBySessionId();
    }

    public FtbTwitchMonitorDto.StrategyDoExecuteCalloutDto doExecuteCallout(String keyParam){
        FtbTwitchMonitorDto.StrategyDoExecuteCalloutDto result = new FtbTwitchMonitorDto.StrategyDoExecuteCalloutDto(String.isBlank(this.twitchUser.AccessToken__c));
        result.outcome = this.twitchUser.Id;
        return result;
    }

    public HttpRequest setAdditionalHeaders(HttpRequest req){
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        return req;
    }

    public HttpRequest setParamsOrBody(HttpRequest req, String params){
        List<TwitchApp__c> appCredentials = FtbTwitchUtility.getTwitchApp();
        req.setBody(generateBody(appCredentials[0].ClientId__c, appCredentials[0].ClientSecret__c, params));
        return req;
    }

    public FtbTwitchMonitorDto.FacadeResponse handleResponse(HttpResponse res){

        FtbTwitchMonitorDto.FacadeResponse response = new FtbTwitchMonitorDto.FacadeResponse(); 

        if(res.getStatusCode() != 200){
            throw new FtbTwitchException('Unable to Token User: ' + res.getStatusCode() + ' ' + res.getStatus(), String.valueOf(FtbTwitchEnums.FtbTwitchErrors.AUTH_ERROR));
        }

        FtbTwitchMonitorDto.TwitchAuthUserResponse authResponse = (FtbTwitchMonitorDto.TwitchAuthUserResponse)JSON.deserialize(res.getBody(), FtbTwitchMonitorDto.TwitchAuthUserResponse.class);

        TwitchUser__c twitchUser = new TwitchUser__c(
            Id = this.twitchUser.Id, 
            AccessToken__c = authResponse.access_token, 
            RefreshToken__c = authResponse.refresh_token);
        
        response.sobjToUpsert.add(twitchUser);
        response.operationOutcome = this.twitchUser.Id;
        
        return response;
    }

    private String generateBody(String clientId, String clientSecret, String code){
        return 'client_secret=' + clientSecret + '&client_id=' + clientId + '&code=' + code + '&grant_type=authorization_code&redirect_uri=' + FtbTwitchConstants.REDIRECT_URI;
    }

}