force-app/main/default/objects/TwitchApp__c/TwitchApp__c.object-meta.xml
<CustomObject>
    <description>Represent the application created via the Twtich Developer Console</description>
    <label>Twitch App</label>
    <nameField>
        <label>Twitch App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchApp__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client ID</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchLog__c/TwitchLog__c.object-meta.xml
<CustomObject>
    <label>Twitch Log</label>
    <nameField>
        <label>Twitch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FtbTwitchServiceInitializer.cls
public with sharing class FtbTwitchServiceInitializer {


    public static string generateTwitchLoginUrl(String additionalScopes){
        try{
            String defaultScope = 'channel:manage:polls channel:read:polls channel:manage:raids';
            if(String.isNotBlank(additionalScopes)){
                defaultScope += ' ' + additionalScopes;
            }
            String baseUrl = Url.getOrgDomainUrl().toExternalForm();
            String apexPage = baseUrl + '/apex/ftbTwitchInitializerFinalizePage';
            String responseType = 'code';
            List<TwitchApp__c> appCredentials = FtbTwitchUtility.getTwitchApp();
            String clientId = appCredentials[0].ClientId__c;
            String baseEndpoint = 'https://id.twitch.tv/oauth2/authorize';
            String fullUrl = baseEndpoint + '?client_id=' + clientId + '&redirect_uri=' + apexPage + '&response_type=' + responseType + '&scope=' + EncodingUtil.urlEncode(defaultScope, 'UTF-8');
            return fullUrl;
        } catch(Exception e){
            FtbTwitchTelemetryService.logException(e.getMessage(), e.getTypeName(), new TwitchLog__c());
        }
        return '';
    }


}