force-app/main/default/objects/TwitchApp__c/TwitchApp__c.object-meta.xml
<CustomObject>
    <description>Represent the application created via the Twtich Developer Console</description>
    <label>Twitch App</label>
    <nameField>
        <label>Twitch App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwitchApp__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client ID</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TwitchApp__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/FtbTwitchAuthApp.cls
public with sharing class FtbTwitchAuthApp implements FtbITwitchInvokeStrategy{

    private String appId;

    public HttpRequest setAdditionalHeaders(HttpRequest req){
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        return req;
    }

    public Boolean doExecuteCallout(String keyParam){
        List<TwitchApp__c> appCredentials = FtbTwitchUtility.getTwitchApp();

        return String.isBlank(appCredentials[0]?.AccessToken__c);
    }

    public HttpRequest setParamsOrBody(HttpRequest req, String params){

        // App auth is formatted in x-www-form-urlencoded
        List<TwitchApp__c> appCredentials = FtbTwitchUtility.getTwitchApp();

        this.appId = appCredentials[0].Id;

        req.setBody(generateBody(appCredentials[0].ClientId__c, appCredentials[0].ClientSecret__c));

        return req;
    }

    public FtbTwitchMonitorDto.FacadeResponse handleResponse(HttpResponse res){

        FtbTwitchMonitorDto.FacadeResponse response = new FtbTwitchMonitorDto.FacadeResponse(); 

        if(res.getStatusCode() != 200){
            throw new FtbTwitchException('Error: ' + res.getStatusCode() + ' ' + res.getStatus(), String.valueOf(FtbTwitchEnums.FtbTwitchErrors.AUTH_ERROR));
        }

        FtbTwitchMonitorDto.TwitchAuthAppResponse authResponse = (FtbTwitchMonitorDto.TwitchAuthAppResponse)JSON.deserialize(res.getBody(), FtbTwitchMonitorDto.TwitchAuthAppResponse.class);

        response.operationOutcome = String.valueOf(FtbTwitchEnums.FtbTwitchOutcome.SUCCESS);
        response.sobjToUpsert.add(new TwitchApp__c(Id = this.appId, AccessToken__c = authResponse.access_token));
        
        return response;
    }

    private string generateBody(String clientId, String clientSecret){
        return 'client_id=' + clientId + '&client_secret=' + clientSecret + '&grant_type=client_credentials';
    }

}