force-app/main/default/objects/FtbTwitchAdapter__mdt/FtbTwitchAdapter__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to define default adapter</description>
    <label>Twitch Adapter</label>
    <pluralLabel>Twitch Adapters</pluralLabel>
</CustomObject>

force-app/main/default/objects/TwitchInvokerStrategy__mdt/TwitchInvokerStrategy__mdt.object-meta.xml
<CustomObject>
    <description>Strategy definitions for the twitch strategy invocation</description>
    <label>Twitch Invoker Strategy</label>
    <pluralLabel>Twitch Invoker Strategies</pluralLabel>
</CustomObject>

force-app/main/default/objects/TwitchInvokerStrategy__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the configuration is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TwitchInvokerStrategy__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint to invoke</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwitchInvokerStrategy__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method of the callout</description>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TwitchInvokerStrategy__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Timeout of the callout</description>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TwitchLog__c/TwitchLog__c.object-meta.xml
<CustomObject>
    <label>Twitch Log</label>
    <nameField>
        <label>Twitch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Twitch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FtbTwitchInvokeFacade.cls
public with sharing class FtbTwitchInvokeFacade extends FtbTwitchBaseClass{

    private FtbTwitchAdapter__mdt adpaterImplSettings;
    
    private TwitchInvokerStrategy__mdt strategySettings;

    private FtbITwitchAdapter adapter;

    private FtbITwitchInvokeStrategy strategy;

    public FtbTwitchInvokeFacade(String strategyName) {
        TwitchInvokerStrategy__mdt strategyRecord = TwitchInvokerStrategy__mdt.getInstance(strategyName);
        
        if(strategyRecord?.Id == null || !strategyRecord?.Active__c){
            throw new FtbTwitchException('Unimplemented Strategy');
        }

        this.strategySettings = strategyRecord;
        this.adpaterImplSettings = FtbTwitchAdapter__mdt.getInstance('FtbTwitchAdapterImpl');

        adapter = (FtbITwitchAdapter)(Type.forName(this.adpaterImplSettings.DeveloperName)).newInstance();
        strategy = (FtbITwitchInvokeStrategy)(Type.forName(this.strategySettings.DeveloperName)).newInstance();
    }

    public String operate(){

        TwitchLog__c log = new TwitchLog__c();

        try{ 
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            HttpResponse res = new HttpResponse();

            req.setEndpoint(this.strategySettings.Endpoint__c);
            req.setMethod(this.strategySettings.Method__c);
            req.setTimeout(Integer.valueOf(this.strategySettings.Timeout__c));
    
            req = this.strategy.setAdditionalHeaders(req);
            req = this.strategy.setParamsOrBody(req);

            log = this.logRequest(req.getBody(), log);

            res = this.adapter.submitRequest(req);

            return this.strategy.handleResponse(res).operationOutcome;
        } catch(Exception e){
            throw new FtbTwitchException(e.getMessage(), this.strategySettings.DeveloperName, log);
        }


    }

    public override TwitchLog__c logRequest(String reqBody, TwitchLog__c log){
        return FtbTwitchTelemetryService.logCalloutRequest(
            this.strategySettings.Method__c,
            this.strategySettings.Method__c,
            reqBody,
            this.strategySettings.DeveloperName,
            log);
    }


}